---
- name: Common failed-deploy cleanup tasks
  hosts: etcd:nodes:masters
  tasks:
    - name: Uninstall previously install packages
      package: name={{item}} state=absent
      with_items:
        - openshift
        - openshift-*
        - etcd
        - docker
        - docker-common

#    - name: Remove atomic-openshift files
#      file:
#        path: "{{item.path}}" #correction code
#        state: absent
#      with_fileglob:
#        - "/etc/sysconfig/atomic-openshift*"
#        - "/etc/sysconfig/docker*"

    - name: remove files and directories
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/origin
        - /var/lib/openshift
        - /etc/etcd
        - /var/lib/etcd
        - /root/.kube
        - /etc/ansible/facts.d
        - /usr/share/openshift
        - /var/lib/docker

- name: Rollback etcd nodes
  hosts: core-01.cary.shackspacehosting.com
  tasks:
#    - name: vmm destroy
#      command: /usr/sbin/bhyvectl --destroy "--vm={{ item }}"
#        - etcd-01
#        - etcd-02
#        - etcd-03

    - name: zfs rollback
      command: zfs rollback -r "zfs01/apiary/{{ item }}.cary.shackspacehosting.com/disk00@pre-ocp-deploy-awx"
      with_items:
        - etcd-01
        - etcd-02
        - etcd-03
