---
deployment_type: origin

# This are overridden on the command line
#ocp_ldap_bind_password: ''
#ocp_router_certfile: "STAR.pods.origin.shackspacehosting.com.crt"
#ocp_router_keyfile: "STAR.pods.origin.shackspacehosting.com.key"
#ocp_router_cafile: "CombinedCARoot.crt"
#ocp_master_named_certfile: "origin.shackspacehosting.com.crt"
#ocp_master_named_keyfile: "origin.shackspacehosting.com.key"
#ocp_master_named_cafile: "CombinedCARoot.crt"
#ocp_ldap_identity_provider_cafile: "CombinedCARoot.crt"

openshift_hosted_router_certificate: {"certfile": "{{ ocp_router_certfile }}", "keyfile": "{{ ocp_router_keyfile }}", "cafile": "{{ ocp_router_cafile }}"}

openshift_master_overwrite_named_certificates: true
openshift_master_named_certificates: [{"certfile": "{{ ocp_master_named_certfile }}", "keyfile": "{{ ocp_master_named_keyfile }}", "cafile": "{{ ocp_master_named_cafile }}"}]

# Basic setup for FreeIPA server, using email address for login.  Use 'uid' instead of 'mail' to use the username
# instead of email address.  This FreeIPA server is setup with a valid certificate and root domain of
# shackspacehosting.com  An ocplookups user was added allowing the OpenShift cluster to view user information without
# allowing anonymous access.  This user can only view required information about users which have access to OpenShift.
openshift_master_identity_providers: [{'name': 'idm', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['mail']}, 'bindDN': 'uid=ocplookups,cn=users,cn=accounts,dc=shackspacehosting,dc=com', 'bindPassword': '{{ ocp_ldap_bind_password }}', 'ca': '{{ ocp_ldap_identity_provider_cafile }}', 'insecure': 'false', 'url': 'ldaps://idm.shackspacehosting.com:636/cn=users,cn=accounts,dc=shackspacehosting,dc=com?mail'}]



os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
openshift_master_default_subdomain: pods.origin.shackspacehosting.com
openshift_master_cluster_public_hostname: origin.shackspacehosting.com
openshift_clock_enabled: true

openshift_metrics_deploy: true
openshift_logging_deploy: true

#openshift_enable_service_catalog: true
#openshift_template_service_broker_namespaces: ['openshift']
osm_use_cockpit: true
openshift_master_cluster_method: native

openshift_hosted_registry_storage_kind: nfs
openshift_hosted_registry_storage_access_modes: ['ReadWriteMany']
openshift_hosted_registry_storage_host: nfs-registry.san.origin.cary.shackspacehosting.com
openshift_hosted_registry_storage_nfs_directory: /exports/openshift
openshift_hosted_registry_storage_volume_name: registry
openshift_hosted_registry_storage_volume_size: 10Ti
openshift_hosted_registry_storage_labels: {'storage': 'registry'}

openshift_metrics_storage_kind: nfs
openshift_metrics_storage_access_modes: ['ReadWriteOnce']
openshift_metrics_storage_host: nfs-metrics.san.origin.cary.shackspacehosting.com
openshift_metrics_storage_nfs_directory: /exports/openshift
openshift_metrics_storage_volume_name: metrics
openshift_metrics_storage_volume_size: 10Ti
openshift_metrics_storage_labels: {'storage': 'metrics'}

openshift_logging_storage_kind: nfs
openshift_logging_storage_access_modes: ['ReadWriteOnce']
openshift_logging_storage_host: nfs-logging.san.origin.cary.shackspacehosting.com
#openshift_hosted_logging_storage_nfs_directory: /exports/openshift
#openshift_hosted_logging_storage_volume_name: logging
openshift_logging_storage_nfs_directory: /exports/openshift
openshift_logging_storage_volume_name: logging

openshift_logging_storage_volume_size: 10Ti
openshift_logging_storage_labels: {'storage': 'logging'}

hostinit_additional_packages: [docker, docker-common, httpd-tools]
#Enabled implies started
hostinit_additional_enabled_services: [docker]
